nelmio_api_doc:
    documentation:
        info:
            title: Sezane
            description: Shop API
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
